### ISSUE TITLE
Assistants install button

### ISSUE THREAD

**Issue by jedrichards** [sketch-hq/sketch-assistants#118]
Since we [decided against](https://github.com/sketch-hq/sketch-assistants/issues/73) using a web service helper to facilitate Assistant installation from web pages, this means some additional requirements around the "Add this Assistant to your Sketch document" button on Assistant details pages on sketch.com.

Ultimately, when a user clicks to add an Assistant they need to open a link in the format:

```
sketch://add-assistant?url=<assistant-tarball-url>
```

Where `assistant-tarball-url` is the full url to the current latest version of that Assistant, as a downloadable tarball. The only way to get this tarball url is to communicate with npm - and without a web service helper, we have to do it clientside (either when the user clicks the install button, or on page load or similar):

Pseudo code something like the below (missing click handler, error handling etc):

```js
const pkg = '@sketch-hq/sketch-tidy-assistant' // Package name for current detail page
const res = await fetch(`https://registry.npmjs.org/${pkg}`, {
  headers: { Accept: 'application/vnd.npm.install-v1+json' }, // This header returns a minimal response
})
const data = await res.json()
const latestVersion = data['dist-tags'].latest
const tarball = data.versions[latestVersion].dist.tarball
const sketchLink = `sketch://add-assistant?url=${tarball}` // Open/redirect to this link
```

**Comment by christianklotz** [comment]
Looking at https://www.sketch.com/extensions/assistants/@sketch-hq/sketch-naming-conventions-assistant/ this already seems be done as described above.
