### ISSUE TITLE
Editable ruleDescription 

### ISSUE THREAD

**Issue by mromanbanks** [sketch-hq/sketch-assistants#139]
Would be great to have an opportunity to override `ruleDescription`. It will allow to teams set their own tone of voice inside assistants

**Comment by ronijaakkola** [comment]
I second this. This would be very useful when extending rules that are highly configurable such as `name-pattern` rules.

**Comment by whakkee** [comment]
removing this from the issues board as this is a feature request and not a production bug or crash or whatever
