### ISSUE TITLE
Allow library ids to be used in the *-allowed-libraries rules

### ISSUE THREAD

**Issue by jedrichards** [sketch-hq/sketch-assistants#143]
It seems that for some users library names are likely not a robust enough approach, and there should be the option to alternatively use library ids.

**Comment by christianklotz** [comment]
Currently all `*-allowed-libraries` specify the Libraries by name in `libraries`, see [library-layer-styles-allowed-libraries](https://github.com/sketch-hq/sketch-assistants/tree/main/assistants/core/src/rules/library-layer-styles-allowed-libraries).

Should this be done as a separate options `libraryNames` and `libraryIds` or less explicitly by allowing different types, UUIDs and name strings as part of the `libraries` option?
