### ISSUE TITLE
Better explanations for assistant rule reasoning?

### ISSUE THREAD

**Issue by Arkkimaagi** [sketch-hq/sketch-assistants#146]
These assistants provided by Sketch seem nice and I really love that there are recommendations on artboard naming and such, but I'd really love to see a bit of reasoning or examples behind the decisions. Is there a "good conventions" guide somewhere that I'm missing as just seeing this:

> Artboard names should start with numbers followed by a space

and then seeing this when I click the question mark:

> Artboard names should start with numbers followed by a space, e.g. 1.1 Splash Screen.

does not tell me why I should be doing this and in what cases.

After seeing this rule, I'm left wondering is there some good convention I have missed? Is there a specific use case that does not apply to us?

I'd hope there be a bit more documentation on the linked .md, or even a link to a blogpost explaining the reasonings behind these default settings.

**Comment by Arkkimaagi** [comment]
Only after pondering a while I realised that the link in "Artboard" really does take you to the corresponding documentation:

https://github.com/sketch-hq/sketch-assistants/tree/main/assistants/core/src/rules/name-pattern-artboards

I still do not see any reasoning for the default settings or a clear path on where to write my own regex pattern in the UI.

**Comment by ronijaakkola** [comment]
I believe that currently you cannot write your own regex patterns in the UI. The main reason Sketch is offering those basic assistants is to showcase how you can extend rules from other assistants. Basically you need to create a custom assistant and extend those name pattern rules with your own regex patterns. More info about extending rules in the documentation: https://developer.sketch.com/assistants/extend-assistants

What it comes to the reasoning behind the default settings, I think it is just a matter of preference. Up to this day Sketch has not released any recommended naming conventions. Most of the teams I have worked with have had a different set of naming conventions. Some use numbers before artboards, some I have seen using emojis. I'm going to write a custom assistant for my current team and extend the basic core rules to support our current conventions.

**Comment by Arkkimaagi** [comment]
If they're examples, I'd prefer them to be clearly labeled as such, or at least explained in the linked documentation.

I'm not afraid of creating my own extensions, but to me the way these assistants are marketed sounds like they should have a bit more UI built around them.

**Comment by christianklotz** [comment]
As far as the [Naming Conventions Assistant](https://www.sketch.com/extensions/assistants/@sketch-hq/sketch-naming-conventions-assistant/) goes it feels like the README/documentation is pretty succinct. Bear in mind that these are the naming conventions we use at Sketch, other teams and organisations may have different preferences and requirements. I am quite curious what conventions people generally follow though.

It's also worth pointing out that Assistant rules come with multiple layers of information:

- **Title** describing the expectation enforced by the rule, displayed within the panel
- **Description** providing the rationale why the rule exists, shown as tooltip
- **Report items** showing the name of document elements violating a rule in the panel, and the message as tooltip
- **Rule ? icon** taking you to `{assistant-homepage}#{rule-name}`

See https://developer.sketch.com/assistants/rules-and-reports for more details, especially the on [rule description](https://developer.sketch.com/assistants/rules-and-reports#rule-descriptions).

If you want to create an Assistant for your own naming conventions, it indeed requires some coding, extending our Core Assistant rules. There's no UI at present. The [template](https://github.com/sketch-hq/sketch-assistant-template) is a good start.

I'm closing this issue for now but you may be interested in tracking #139 as this could provide more options to provide meaningful information to designers using Assistants.
