### ISSUE TITLE
'artboards-layout' and 'artboard-grids' showing non-compliant status when grids and layouts are hidden 

### ISSUE THREAD

**Issue by mariuszmickiewicz** [sketch-hq/sketch-assistants#147]
Sketch default rules `artboards-layout` and `artboard-grids` mark artboards as non-compliant when I turn off the visibility(!)  of the layout or grid. I think it only should check the numbers and if the layout settings are on (checkbox) and not the visibility state (designers keep turning layout/grid on and off all the time and assistant notification changing their state based on this is misleading).

Here is my assistant: 
https://github.com/carbon-design-system/carbon-sketch-assistant

**Comment by jedrichards** [comment]
This seems like a very valid problem. Cross referencing with https://github.com/sketch-hq/sketch-assistants/issues/135 too, which could be tackled at the same time.

**Comment by ines-sketch** [comment]
Moving to QA from done as I was not aware of the process for this.
@smithzoo can you take a look when you can, please? 🙏  The PR is [here](https://github.com/sketch-hq/sketch-assistants/pull/162).

**Comment by smithzoo** [comment]
Loaded up the carbon assistant and I am not getting any change in violations based solely on grid or layout visibility being toggled (testing current 70.2 release). Checking with @jedrichards to see if the fixes were merged, as it seems that way.

**Comment by mariuszmickiewicz** [comment]
I just updated Carbon assistant to have these updates included. My original request was to check all of the artboards which have layout set up and **turned on** (checkbox inside the Layout Settings popup) and not based on the **visibility** of the layout and currently it seems that this is working well.

PR above seems to be talking about **visibility** of the layout… 

I'm happy with the updates, but they seems to describe something else than what they actually do (maybe I'm misinterpreting something).

**Comment by mariuszmickiewicz** [comment]
I see the pull request which hasn't been yet approved. Does it mean the rules again will work only for the visible layouts?

**Comment by jedrichards** [comment]
@mariuszmickiewicz The change has been done here in the repo, but nothing has been released yet to npm. Hopefully that's about to happen real soon!

**Comment by jedrichards** [comment]
@mariuszmickiewicz We're just QAing this at the moment, and wanted to confirm the new behaviour with you.

The problem you reported is basically that toggling off grid and layout visibility with `control-g` and `control-l` wouldn't remove associated violations from these two rules. And the change you suggested was that when grids and layouts are not visible, then these two rules shouldn't raise violations related to invalid settings?

Do we have that right?

**Comment by mariuszmickiewicz** [comment]
@jedrichards 
Not exactly :) If I remember well the original issue was that artboards with hidden (hidden, and not turned off) layout were marked as violating the rules (even if the layout was from the list of allowed ones). Somehow Sketch decided these don't have any layout (I guess) and hence violate the rule.  

My suggestion was to ignore _visibility_ state all together (as designers hide/show the layout often and don't need to see violations for the properly set up, but hidden layouts) and check only if all of the settings are matching those from the provided list. 

Additionally (and I don't know what's best approach here) if the grid is set up, but turned off (not hidden) or artboard doesn't have a grid at all then maybe it shouldn't violate the rule (some support artboards which are not really a UI / product based)?

**Comment by jedrichards** [comment]
Hello all we are closing this one in favour of https://github.com/sketch-hq/sketch-assistants/issues/167 since we found some deeper issues with the current setup, and proposals here.

@mariuszmickiewicz Feel free to comment on the new issue if you like :)
