### ISSUE TITLE
Add prefer colour variable rule

### ISSUE THREAD

**Issue by christianklotz** [sketch-hq/sketch-assistants#148]
Similar to [layer-styles-prefer-shared](https://github.com/sketch-hq/sketch-assistants/tree/main/assistants/core/src/rules/layer-styles-prefer-shared) a new rule should suggest to use colour variables.

It should expose one option `maxIdentical` to allow people to define how often a colour value can be set within a document without nudging to use colour variables.

**Comment by jedrichards** [comment]
@smithzoo We'd like your help QA this if possible 🙂

Ping me when you're ready.

## QA Steps

- Check out the next release https://github.com/sketch-hq/sketch-assistants/pull/154
- From the root run `yarn build`
- Change to the Reuse Suggestions Assistant package `cd assistants/reuse-suggestions`
- Build its tarball `yarn package-tarball`
- Add the tarball to a Sketch 69+ document

The Reuse Suggestion Assistant should complain about more than 2 usages of a hard coded color, suggesting to use a color variable instead. It checks colors in the following places:

- Artboard, Slice and Symbol Master backgrounds
- Borders, Fills, Shadows and Inner Shadows of layer styles
- Colors applied to text strings

**Comment by smithzoo** [comment]
@jedrichards still checking a few things but these jumped out at me:

* I don't think disabled background colors for Artboards should be included. As it stands, creating 3 artboards w/o implicitly setting a background color (default), the error will be triggered. We do not include disabled fills/strokes.
* Tooltip for colors is incorrectly showing 8 characters when the HEX is six. Looks like we're adding `FF` to the end.
<img width="704" alt="Screen Shot 2020-09-21 at 8 50 09 AM" src="https://user-images.githubusercontent.com/4378001/93768632-ae639380-fbe7-11ea-84d1-9cce6fa00056.png">

**Comment by jedrichards** [comment]
@smithzoo Thanks Evan, all good/valid remarks. I'll sort these tomorrow morning 👍

**Comment by jedrichards** [comment]
@smithzoo This is ready for another look 🙇‍♂️

**Comment by smithzoo** [comment]
@jedrichards excellent, works exactly as expected!

**Comment by bomberstudios** [comment]
Sounds like this one can be closed already, @christianklotz?
