### ISSUE TITLE
Allow placing layers on subpixels if a specific keyword is used in symbol artboard

### ISSUE THREAD

**Issue by dkasaj** [sketch-hq/sketch-assistants#163]
Icons tend not to place layers on 0.0 and 0.5 pixel increments. 

It gets tedious clicking warnings one by one (a single icon might have 10 such layers) for standard fontawesome icons etc.

Imagine how wonderful it would be if the assistant didn't complain when the symbol artboard contained a keyword like #allowsubpixels

**Comment by bomberstudios** [comment]
Good one.

We could definitely use the Assistant configuration to define keywords to skip checks on certain layers.

**Comment by dkasaj** [comment]
Closed without any explanation?
