### ISSUE TITLE
Images should not trigger a violation for layer-styles-prefer-shared rule

### ISSUE THREAD

**Issue by konki-vienna** [sketch-hq/sketch-assistants#170]
Layer type 'Image' should probably be added to `IGNORE_CLASSES`.
https://github.com/sketch-hq/sketch-assistants/blob/main/assistants/core/src/rules/layer-styles-prefer-shared/index.ts#L14

**Comment by jedrichards** [comment]
Rather than completely ignore image layers, perhaps what we'd rather do is ignore image layers that have default styles?

**Comment by konki-vienna** [comment]
Yes, that would be possibly preferred. Is there an easy way to check if an image layer has modified styles (=non-default styles)? 🤔

**Comment by konki-vienna** [comment]
> Rather than completely ignore image layers, perhaps what we'd rather do is ignore image layers that have default styles?

Yes, that would be possibly preferred. Is there an easy way to check if an image layer has modified styles (=non-default styles)? 🤔

**Comment by jedrichards** [comment]
@konki-vienna Yeah - exactly. I don't think we have a perfect/explicit way to identify whether a layer still has a default style, it'll just be a case of looking at what the default style data object Sketch gives image layers and checking for it.

So its, is the layer and image and does it have a style that looks as if its default? If so escape the loop with `continue` ...

**Comment by smithzoo** [comment]
Already merged, good to close.
