### ISSUE TITLE
Add possibility to ignore layer

### ISSUE THREAD

**Issue by kierzniak** [sketch-hq/sketch-assistants#175]
It would be nice to have possibility to ignore layer for some rules. For the first iteration it may be as simple as adding "ignore" keyword to layer or "ignore: some-rule". In the next iteration we can have some interface for that.

I think it is important also to have some list with ignored layers in one place.

**Comment by jedrichards** [comment]
Hi @kierzniak! Ignoring Assistant issues is already possible in the Sketch app itself, see here https://www.sketch.com/docs/assistants/#ignoring-issues

Is that helpful? Or did you have something else in mind?

**Comment by kierzniak** [comment]
Yes! This is exactly what I want. Thank you!
