### ISSUE TITLE
Change config merge behaviour for extended Assistants

### ISSUE THREAD

**Issue by christianklotz** [sketch-hq/sketch-assistants#188]
Currently, extending an Assistant will merge any new Assistant configuration with the configuration provided by the base Assistant. However, any existing rule configs are replaced, not merged, by newly provided rule configs.

Given an original configuration such as:

```ts
{
  rules: {
    'rule-1': {
      active: true,
    },
    'rule-2': {
      active: true,
      foo: 1,
    },
    'rule-3': {
      active: true,
      bar: "hello",
      baz: "world",
    },
  }
}
```

… extending the Assistant with the following config:

```ts
{
  rules: {
    'rule-1': {
      active: false,
    },
    'rule-3': {
      active: true,
      baz: "everyone",
    },
}
```

… will result in:

```ts
{
  rules: {
    'rule-2': {
      active: true,
      foo: 1,
    },
    'rule-3': {
      active: true,
      baz: "world",
    },
  }
}
```

This configuration is invalid because `rule-3` does not include all required properties with `bar` missing. One option is to always provide a full configuration for each rule but this seems inconsistent given that the Assistant configuration overall can be partial.

Instead of shallow merging `rules`, it would be better to deep merge them as it makes it easier to tweak existing Assistants.

**Comment by jedrichards** [comment]
I think your final code block above should be

```js
{
  rules: {
    'rule-1': {
      active: false,
    },
    'rule-2': {
      active: true,
      foo: 1,
    },
    'rule-3': {
      active: true,
      baz: "everyone",
    },
  }
}
```

**Comment by christianklotz** [comment]
Right, indeed … I omitted the one with the `active: false`. Your version is the desired one.
