### ISSUE TITLE
Improve cache iteration API

### ISSUE THREAD

**Issue by jedrichards** [sketch-hq/sketch-assistants#20]
At the moment cache iteration is achieved via a callback based approach:

```typescript
utils.iterateCache({
  textLayer(node: Node) {
    // Perform rule logic
  }
})
```

This is all well and good, but it's potentially overly-complex and quite inflexible. If instead we exposed standard [iterable objects](https://javascript.info/iterable) for the various cache items then it enables a host of flexible approaches using native language features out of the box

- `for ... of` loops
- Await promises in the loops
- Convert to arrays with `Array.from`
- Using array spread syntax
- And more

Additionally if the iterable objects were properly typed we could avoid some of the type casting gymnastics we're doing at the moment in rules. i.e. casting from a generic `Node` to a more specific type like `Node<FileFormat.TextLayer>`.

Proposed syntax to loop a cache item

```typescript
for (const textLayer of utils.iterators.textLayers) {
  // textLayer is typed as Node<FileFormat.TextLayer>
  // Perform rule logic
}
```

Once the new API is available rule utils, then we can transition the core rules to make use of it, and in due course remove the old iteration api.

**Comment by christianklotz** [comment]
This is waiting for https://github.com/sketch-hq/sketch-assistant-core-rules/issues/125?

**Comment by jedrichards** [comment]
@christianklotz Yeap.
