### ISSUE TITLE
Remove `symbols-no-unused` rule from the Tidy assistant

### ISSUE THREAD

**Issue by jedrichards** [sketch-hq/sketch-assistants#23]
**UPDATE:**
After some discussion it was determined that this rule is too strict and not very useful, so it's best to simply remove it from the assistant for now.

**Summary**
I'm being told by the "Tidy" assistants I should use symbols, on artboards that **are** symbols.

**Steps to Reproduce**
Steps required to reproduce the problem:
1. Opened [comments-annotations.sketch.zip](https://github.com/sketch-hq/Sketch/files/4574030/comments-annotations.sketch.zip)
2. Ran the "Tidy" assistant
3. View Results
4. See:

<img width="529" alt="Screenshot 2020-05-04 at 11 24 23" src="https://user-images.githubusercontent.com/4420570/80956796-cfbf1100-8df9-11ea-8f4a-f5e61d93912e.png">

My only inkling is I may have created these particular symbols by duplicating another and then renaming it. Perhaps it's picking up some history there and erroneously flagging it?

cc @jedrichards @carmenlanza

**Comment by jedrichards** [comment]
Looks like the rule is probably neglecting to search through symbols being used as overrides.

**Comment by jedrichards** [comment]
### QA

- Checkout the branch
- In the root, `yarn` and then `yarn build`
- `cd assistants/tidy`
- `yarn package-tarball`
- Test in Sketch, confirm that a symbol only used as a value in an another symbols override doesn't trigger a "Symbol should be used" violation

**Comment by smithzoo** [comment]
@jedrichards Tidy doesn't seem to be reporting any violations for me (outside of artboards or unused symbols. Using SHA `a4d57877` from `fix/count-overrides-as-used-symbols`, current Experimental build with the attached `.tgz` and file.
[Archive.zip](https://github.com/sketch-hq/sketch-assistants/files/4662782/Archive.zip)

**Comment by smithzoo** [comment]
the original issue that was reported, which i completely misread, is that if an artboard itself is a symbol, it's not being counted as in use. Artboards as symbols seem to be handled differently by the app in general.

* If you create an artboard and convert it to a symbol, it is not added to the `Symbols` page.
* If you add an artboard on the Symbols page directly, convert it to a symbol, and then insert the instance on the page...no violation but it does not appear like other artboards.

**Comment by smithzoo** [comment]
@jedrichards Change of direction, just remove the rule per our discussion in Slack https://sketch.slack.com/archives/CK9MW0PL2/p1590080701029300?thread_ts=1590069730.020500&cid=CK9MW0PL2

**Comment by jedrichards** [comment]
@smithzoo Ok it's removed from Tidy. Same instructions as above should allow you to confirm.

**Comment by smithzoo** [comment]
Verified successful removal of the symbols-unused rule.
