### ISSUE TITLE
Detect detached symbols

### ISSUE THREAD

**Issue by jedrichards** [sketch-hq/sketch-assistants#24]
There has been a lot of user research and feedback from designers saying that detecting the presence of "detached symbols" will be a super useful rule to have.

So this means detecting when a user has clicked "Detach from symbol" on a symbol instance, and converted it to a plain group, breaking the link with the symbol master. This can be a major problem in large organisations that require strict adherence to design systems using libraries and symbols.

This issue is to discuss how to implement a rule that achieves this. This is tricky because, as far as I know, once a symbol has been detached and converted into a group there is no record in the file JSON that the group was ever previously a symbol instance.

One idea has been to update Sketch to record a note in the group's `userInfo` property that it was previously a symbol instance ...

Or is there another way?

**Comment by christianklotz** [comment]
May be blocked by https://github.com/sketch-hq/Sketch/issues/29516

**Comment by jnozzi** [comment]
Heads up: #29516 has been submitted for CR. :-)

**Comment by sonburn** [comment]
Is it worth differentiating between _how_ the symbol instance was detached? If the instance was detached because the symbol was deleted, or something along those lines, then I think this will be really helpful. But if the instance was detached by the user manually, in order to make a modification that the symbol didn't allow for, then will it be more of a nuisance to get alerts about it?

**Comment by jedrichards** [comment]
@sonburn Including a reason why the symbol was detached (e.g. symbol deleted vs. user clicked detach etc) is a neat idea, and could perhaps be useful for various use cases.

But as for whether certain sorts of Assistant results could be a nuisance, the hope is that teams will be able to fine tune their experience to suit their internal workflows and processes. Adding an Assistant to a document is optional, and even once added you'll be able to silence or mute certain sorts of results if they just get in the way. Or the ultimate escape hatch is to write your own Assistants that work the way you need them to - you can write these from scratch, or extend from other Assistants to piggy-back on their functionality.
