### ISSUE TITLE
Fix Assistant homepage links

### ISSUE THREAD

**Issue by jedrichards** [sketch-hq/sketch-assistants#25]
Currently they are pointing to a non-existent location in the GitHub repo.

### QA

1. Clone this repository
1. Package the 3 assistants into local tarballs
1. Install these to a Sketch document using the _Install from Disk_ option
1. Ensure the Assistant "Learn more" buttons do not 404 and lead to the correct pages

**Comment by smithzoo** [comment]
@jedrichards Still getting 404s after building locally and installing:

- https://github.com/sketch-hq/sketch-assistants/tree/master/packages/tidy#@sketch-hq/sketch-assistant-core-rules/layers-no-loose
- https://github.com/sketch-hq/sketch-assistants/tree/master/packages/naming-conventions#@sketch-hq/sketch-assistant-core-rules/name-pattern-pages

**Comment by jedrichards** [comment]
@smithzoo Hmm, seem to be working for me when testing locally. Shall we screenshare or something and go through the local build and test procedure, and see if we're going anything different? I think it's worth trying to sort it out ...

**Comment by christianklotz** [comment]
@smithzoo can you give this another try, with @jedrichards help if needed. It would be good to get this out.

**Comment by smithzoo** [comment]
URLs now resolve correctly for all 3 assistants we are providing.

### Validation Details: 

- **Branch:** `fix/25-homepage-values`
- **Built from commit:** 3aaaa9d1
- **Sketch version (build):** n/a
- **OS:** macOS 10.15.3, 10.14.6
- **Hardware:** MacBook Pro (15", 2019) Retina w/ external 4k display, Mac mini (2018) w/ 4k display

### Verification Notes: 

- [ ] Reviewed open PR notes and diff
- [ ] Code review comments checked for resolution
- [ ] Reviewed existing test coverage for scope & changes
- [ ] Original report steps reviewed and retested
- [ ] Copy & Spelling check performed
- [ ] i18n check performed
- [ ] Happy path validation performed
- [ ] Notion Specifications tested against
- [ ] Visual design mocks have been checked against
- [ ] Visual checks made in both Light & Dark UI modes
- [ ] Visual checks made on both Retina & non-Retina displays
- [ ] Performance test carried out 
- [ ] Console checked for errors
- [ ] Validated against Cloud expectations
- [ ] Validated against user Account Permissions/Roles
- [ ] Regressions from this change considered and tested

### Follow Up

- [ ] File related items
- [ ] Milestone & Project assigned to issue 
- [ ] Internal release note added / Release note required
