### ISSUE TITLE
Add icons to Assistants

### ISSUE THREAD

**Issue by jedrichards** [sketch-hq/sketch-assistants#29]

**Comment by jedrichards** [comment]
Icons

![Reuse](https://user-images.githubusercontent.com/1078571/81807090-56b86b80-9515-11ea-8db3-f96e1bdef891.png)

![Tidy](https://user-images.githubusercontent.com/1078571/81807097-5a4bf280-9515-11ea-82a0-60c7d7c01c71.png)

![Naming](https://user-images.githubusercontent.com/1078571/81807101-5f10a680-9515-11ea-8f76-044fbcb4771d.png)

**Comment by jedrichards** [comment]
![Naming](https://user-images.githubusercontent.com/1078571/81808046-0a6e2b00-9517-11ea-9b6c-1c6fa9a377ba.png)

![Tidy](https://user-images.githubusercontent.com/1078571/81808057-0e01b200-9517-11ea-95ae-8759f54dba13.png)

![Reuse](https://user-images.githubusercontent.com/1078571/81808051-0c37ee80-9517-11ea-9bf2-86fc3cf7edcb.png)

**Comment by christianklotz** [comment]
# QA Notes

I don't think there's much to test at this point.
