### ISSUE TITLE
Node CLI

### ISSUE THREAD

**Issue by jedrichards** [sketch-hq/sketch-assistants#38]
A Node CLI for running Assistants outside of Sketch.

**Comment by jedrichards** [comment]
I see two main possible approaches here, with A) probably being the more "normal" way of approaching it.

### A. Stylelint or eslint style tool

Defines active Assistants in a config file. Works in the context of a project with a package.json that defines the dependencies referenced in the config file. Then the CLI is mainly just a way of passing in the Sketch file(s) to be linted.

```sh
sketch-assistants-cli "**/*.sketch"
```

### B. Standalone CLI tool

Run one or more Assistants against some Sketch files just via the CLI, no requirement for an outer package.json. This would dynamically acquire the Assistant packages as needed, and return the results.

```sh
sketch-assistants-cli \
  --assistant=@sketch-hq/sketch-tidy-assistant \
  --assistant=@sketch-hq/sketch-naming-conventions-assistant \
  --assistant=@sketch-hq/sketch-reuse-suggestions-assistant \
  "./**/*.sketch"
```

**Comment by christianklotz** [comment]
**A.** works for me, very much in line with the Sketch environment

**Comment by jedrichards** [comment]
@christianklotz I guess the fundamental question I have is, is the cli driven by the contents of the Assistants Workspace in the Sketch file, or is it driven by an external config file e.g. the equivalent of a `.eslintrc`? Or some combination of the two strategies.

The problem with it being driven by the Assistants Workspace in the Sketch file is that we'd need some way to install the dependencies contained therein before invoking the required Assistants. So that either means programmatically calling `npm` somehow, and then either installing those Assistant packages to the current project, or perhaps installing them to a temporary folder somewhere.

It'd be simpler if we didn't do that, and instead used an external configuration file which independently referenced whatever Assistants were desired, and required that those Assistants were ready to go in `node_modules` before the cli was invoked. This is most similar to how eslint and friends works, but the downside is that the Assistant setup as applied to a Sketch file in Sketch could get out of sync with a cli Assistants project.

Perhaps that's ok initially, and in the future we could think about ways of creating or syncing a Node project folder to match the Assistant config within a Sketch file 🤔

**Comment by christianklotz** [comment]
I see, we basically want to use `yarn`/`npm install` pretty much as is and then invoke the runner.

- The `.sketch/workspace/assistants.json` is a `package.json` but with a different name
- As far as I know, `yarn` and `npm` require there to be a `package.json`, no alternative name

Is there a to "symbol link" into the `assistants.json`? Maybe that's one command, do extract or expose the config?

**Comment by jedrichards** [comment]
The issue is we've in a sense got multiple package.jsons, the one inside the Sketch file(s) workspaces, and the outer/main one which includes the cli itself as a dependency and is the context within which the cli is invoked.

It's a bit weird to have a cli tool mutate or change the main project's package.json, you should keep that under control of the user. Also if you're wanting to run Assistants against multiple Sketch documents do you continually update the outer package.json and run `npm install` between running each document? I don't think this would work in practice.

If we think it's important that the correct Assistants from the file workspaces are used, then that suggests to me that for each run we need to create some sort of temporary sandboxed folder where we extract the Sketch file's assistant.json, rename it to package.json, programmatically call `npm install`. And then do the run inside that.

As I said, the alternative would be much simpler ... effectively ignore the Assistant config in the file workspaces, and reproduce it at the top level.

**Comment by christianklotz** [comment]
Yeah, I think if we're looking at the type of usage scenarios we're primarily looking at validating a document as part of the CI. So I guess the closest thing to reality is something like this:

```sh
sketch-assistant document.sketch
```

Should it accept wild cards?

```sh
sketch-assistant *.sketch
```

or multiple files

```sh
sketch-assistant document-1.sketch document-2.sketch
```

**Comment by christianklotz** [comment]
Maybe one of the options is to pass in whether you want to use `yarn` or `npm`, default to `yarn` or whatever is available on the machine? Don't know what's the best way to specify, some ideas:

```sh
sketch-assistant --package-manager yarn document.sketch
```

```sh
sketch-assistant --yarn document.sketch
```

```sh
sketch-assistant --yarn=/usr/bin/yarn document.sketch
```

**Comment by jedrichards** [comment]
Yeah I think passing in wildcards, a single file or multiple files is quite easy. There are lots of nice modules available to help with argument parsing and that sort of thing these days.

I think probably safe to start with just using `npm` for the Assistants install. After all, this will happen behind the scenes, so shouldn't matter too much to the user which package manager is being used to prepare the dependencies and they are guaranteed to have `npm` on their system if they've managed to invoke a node cli.

Other ideas I had:

- Output could default to something formatted and human readable listing the violations per file etc. But could also have a `--json` flag, to output machine readable results to stdout instead.
- Might be nice to have an optional `--config=./path/to/assistants.json`, where you could supply a custom Assistants setup to use in place of anything found in the workspaces. This would allow running Assistants against a Sketch file that was yet to be configured with Assistants in Sketch.

**Comment by christianklotz** [comment]
Good point on running unconfigured docs, happy with `--config`, same goes for JSON output and human readable by default
