### ISSUE TITLE
Debug Assistant for triggering different violations at different severities

### ISSUE THREAD

**Issue by jedrichards** [sketch-hq/sketch-assistants#49]

**Comment by smithzoo** [comment]
I could use a means to trigger different severities independently of one another to view the different states of the badges:

Page names = info
Must start with an emoji, e.g. 🚧 Work in Progress

Artboard names = warning
Must start with an emojii or be numbered. e.g. 1.1 Splash Screen

Group names = error
Default layer names are forbidden, e.g. Group
