### ISSUE TITLE
Release Assistants and CLI

### ISSUE THREAD

**Issue by jedrichards** [sketch-hq/sketch-assistants#57]
Merges #55 to release `5.0.0-next.15` of the monorepo. This includes the first release of the cli package.

### QA

Build the three Assistants locally from `master` (i.e. package as tarballs), and check they work with the current Sketch Private release.

If they work as expected, then we are good to make the release (i.e. won't be breaking things for our testers).

**Comment by jedrichards** [comment]
@smithzoo One for you. Let me know if anything isn't clear.

**Comment by smithzoo** [comment]
@jedrichards Built & installed Assistants from `master` w/o a problem using last staged Private Beta 67 (99712). Spots checked the rules and found no issues, looks good to go.
