### ISSUE TITLE
QA Release

### ISSUE THREAD

**Issue by jedrichards** [sketch-hq/sketch-assistants#66]
QA `master` branch and ensure that the three Assistants built on it work with Sketch Private.

All being well we can merge the [release](https://github.com/sketch-hq/sketch-assistants/pull/63) PR.

**Comment by smithzoo** [comment]
@jedrichards SHA `83511034 ` looks good to me. All Assistants build, installed and spot checked successfully in latest private beta.

**Comment by jedrichards** [comment]
@smithzoo Thank you!
