### ISSUE TITLE
`layers-no-loose` needs to check whether a layer is ignored before reporting a violation

### ISSUE THREAD

**Issue by jedrichards** [sketch-hq/sketch-assistants#88]
This is causing a rule error with the latest ignore code.

Best to update this rule and release new Assistants once the ignore feature has made its way to Sketch Private.

**Comment by smithzoo** [comment]
Hold off on QA until the updated Assistants are intergrated

**Comment by smithzoo** [comment]
Verified in 68 (102183) with #30997, close when merged
